### ISSUE TITLE
两点建议及解决方案

### ISSUE THREAD

**Issue by clouduan** [chxuan/change-colorscheme#4]
感谢大佬的插件，切换主题从此方便多了！
然后今天我发现两个问题，而且针对以下两点建议提了 PR，因为写在 commits 中并不能完整地表述，所以写在 issue 里方便记录和叙述。
- 1
    - Issue: 在切换主题后，由于原先的主题被换掉，且其在主题列表里的位置不确定，因此我很难再换回原来的主题。
    - Solution: 将所有主题排序，并将当前主题加至主题列表头部，主题的位置索引从0开始，这样只要反向切换即可切回原来的主题。

- 2
    - Issue: 默认主题搜索路径设置为 `~/.vim` 不太全，因为对于 Neovim 用户和 Windows 平台的 Vim 用户来说并**不一定**是这个目录。
    - Solution: 本来打算用 `&rtp` 中的目录来找，但是发现按照 `&rtp` 查找会导致列表主题名重复，好在有个强大的函数 `getcompletion` 可以直接查找得到所有的主题名，这样就可以省去好多函数，包括搜索主题/读取主题/搜索文件/处理路径的这些。

**Comment by chxuan** [comment]
@clouduan 感谢你的意见和优化方案，现在我已将你的优化代码合并到
master分支了，有了getcompletion函数，确实会省事很多。

**Comment by voldikss** [comment]
@chxuan Bingo~ 而且我发现有一些随着 vim/nvim 发布的原生主题不在 `~/.vim` 里，而是放在类似于 `/usr/share/**` 之类的目录里，所以这个函数就能够全部获取到（虽然原生主题很丑基本没有使用价值 :neckbeard:

**Comment by chxuan** [comment]
Vim的安装目录下就有它自带的主题，之前我也查找过它自带的主题了的，就是因为不怎么好看所以就只查找用户自己安装的主题
