### ISSUE TITLE
can we set default theme?

### ISSUE THREAD

**Issue by FesianXu** [chxuan/change-colorscheme#7]
Hi, I am using your vimplus, that's wonderful, and I love it. But i met some troubles when I 'm using colorscheme plugin. I wanna set the default theme but I dont know how to set it. So I could only manully change the theme until reach to my favourite one.

**Comment by chxuan** [comment]
@FesianXu 你好，感谢你使用vimplus，目前change-colorscheme插件还不支持设置主题，只支持主题查看。

**Comment by FesianXu** [comment]
@chxuan 您好，请问vimplus中是否有插件可以支持设置主题呢？我了解到vimplus也是您的作品。

**Comment by chxuan** [comment]
@FesianXu vimplus目前没有集成设置主题的插件，用户想要修改主题，只有编辑~/.vimrc或~/.vimrc.custom.config来修改

**Comment by FesianXu** [comment]
好的，感谢
